version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: compose pull for use latest
          command: docker-compose pull
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose -f docker-compose.yml -f docker-compose_linux.yml -d
            docker-compose exec wp curl -ksfI --retry 10 --retry-delay 5 --retry-connrefused https://localhost/
            docker-compose exec wp curl -ksfI --retry 10 --retry-delay 5 --retry-connrefused https://localhost/wp-admin/install.php
